image: node:latest

stages:
  - assembly
  - build
  - test
  - publish

# cache: {} # Skip cache download
cache: &global_cache
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
  policy: pull-push

GatsbyBuild:
  stage: build
  cache:
    <<: *global_cache
  script:
    - yarn install --silent && yarn gatsby build
  artifacts:
    paths:
      - ./public/*
      - ./lambda/*
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /-(publish|preview)/

# Default behavior is a dummy deploy
NetlifyDeploy:
  stage: publish
  script:
    - yarn add netlify-cli
    - yarn netlify deploy --auth $NETLIFY_AUTH_TOKEN --site $NETLIFY_SITE_ID
  dependencies:
    - GatsbyBuild

# Deploy changes to website if -publish is passed in commit
NetlifyPublish:
  stage: publish
  script:
    - yarn add netlify-cli
    - yarn netlify deploy --auth $NETLIFY_AUTH_TOKEN --site $NETLIFY_SITE_ID --prod
  dependencies:
    - GatsbyBuild
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /-publish/
