image: node:latest

stages:
  - assembly
  - build
  - test
  - publish

# cache: {} # Skip cache download
cache: &global_cache
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
  policy: pull-push

GatsbyBuild:
  stage: build
  cache:
    <<: *global_cache
  script:
    - yarn install --silent
    - yarn gatsby build
    - yarn global add netlify-cli
    - netlify deploy --auth $NETLIFY_AUTH_TOKEN --site $NETLIFY_SITE_ID

# Deploy changes to website if -publish is passed in commi
NetlifyPublish:
  stage: publish
  cache:
    <<: *global_cache
  script:
    - yarn install --silent
    - yarn gatsby build
    - yarn global add netlify-cli
    - netlify deploy --auth $NETLIFY_AUTH_TOKEN --site $NETLIFY_SITE_ID --prod
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /--publish/
